CREATE TABLE "INA_DRIVLOK_COFC"(
 "PCK_NO" VARCHAR(7),
 "ORDER_NO" VARCHAR(7),
 "ORDER_LINE" VARCHAR(4),
 "CUSTOMER" VARCHAR(6),
 "NAME_CUSTOMER" VARCHAR(30),
 "DATE_SHIPPED" DATE,
 "CUSTOMER_PO" VARCHAR(15),
 "PART" VARCHAR(20),
 "CUST_PART" VARCHAR(20),
 "DESCRIPTION" VARCHAR(30),
 "LOT" VARCHAR(15),
 "QUANTITY" DOUBLE
);
